version: '3.8'

services:
  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - '80:80'
    restart: unless-stopped
    networks:
      - app-network

  # 后端服务配置，取消注释并根据需要调整
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - DATABASE_URL=postgresql://user:password@db:5432/dbname
  #   depends_on:
  #     - db
  #   restart: unless-stopped
  #   networks:
  #     - app-network

  # 数据库服务配置，取消注释并根据需要调整
  # db:
  #   image: postgres:13
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_USER=user
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_DB=dbname
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge
# 数据卷配置，取消注释并根据需要调整
# volumes:
#   postgres_data:
