/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as EditImport } from './routes/edit';
import { Route as IndexImport } from './routes/index';
import { Route as DevDashboardImport } from './routes/dev/dashboard';

// Create/Update Routes

const EditRoute = EditImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

const DevDashboardRoute = DevDashboardImport.update({
  id: '/dev/dashboard',
  path: '/dev/dashboard',
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/edit': {
      id: '/edit';
      path: '/edit';
      fullPath: '/edit';
      preLoaderRoute: typeof EditImport;
      parentRoute: typeof rootRoute;
    };
    '/dev/dashboard': {
      id: '/dev/dashboard';
      path: '/dev/dashboard';
      fullPath: '/dev/dashboard';
      preLoaderRoute: typeof DevDashboardImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/edit': typeof EditRoute;
  '/dev/dashboard': typeof DevDashboardRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/edit': typeof EditRoute;
  '/dev/dashboard': typeof DevDashboardRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/edit': typeof EditRoute;
  '/dev/dashboard': typeof DevDashboardRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/edit' | '/dev/dashboard';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/edit' | '/dev/dashboard';
  id: '__root__' | '/' | '/edit' | '/dev/dashboard';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  EditRoute: typeof EditRoute;
  DevDashboardRoute: typeof DevDashboardRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditRoute: EditRoute,
  DevDashboardRoute: DevDashboardRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/edit",
        "/dev/dashboard"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/edit": {
      "filePath": "edit.tsx"
    },
    "/dev/dashboard": {
      "filePath": "dev/dashboard.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
